"""Add sender and ticket relationships to SupportMessage

Revision ID: 56251c2f58f6
Revises: 5656deea4f2b
Create Date: 2025-05-29 14:34:48.645020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56251c2f58f6'
down_revision: Union[str, None] = '5656deea4f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add ticket_id column

    # Add foreign key constraints
    op.create_foreign_key(
        'fk_support_messages_ticket',
        'support_messages', 'support_tickets',
        ['ticket_id'], ['id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_support_messages_sender',
        'support_messages', 'users',
        ['sender_id'], ['id'],
        ondelete='CASCADE'
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
