"""add sales_count to drug

Revision ID: 8ad4590aace1
Revises: d15bc31e63ea
Create Date: 2025-05-27 06:47:56.289942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad4590aace1'
down_revision: Union[str, None] = 'd15bc31e63ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('sales_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drugs', 'sales_count')
    # ### end Alembic commands ###
